# Generated by Django 4.0.3 on 2022-03-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(max_length=200)),
                ('sample_id', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_distance', models.FloatField()),
                ('end_distance', models.FloatField()),
                ('measurement_times', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('board_width', models.FloatField(help_text='Available width to measure on (in cm) - e.g. 50.5')),
                ('measurement_width', models.FloatField(help_text='Width needed for one measurement (in cm) - e.g. 1.8')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='main.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
