# Generated by Django 4.1 on 2022-10-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experiment_started_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='measurement_width',
        ),
        migrations.AddField(
            model_name='setting',
            name='ball_diameter',
            field=models.FloatField(default=4.0, help_text='Diameter of ball in (in cm) - e.g. 1.35'),
        ),
        migrations.AddField(
            model_name='setting',
            name='measurement_gap',
            field=models.FloatField(default=0.5, help_text='Gap between each measurement (in cm) - e.g. 0.5'),
        ),
        migrations.AddField(
            model_name='setting',
            name='stepper_motor_direction_inverted',
            field=models.BooleanField(default=False, help_text='Flips homing direction of stepper motor'),
        ),
    ]
