# Generated by Django 4.1.2 on 2023-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_setting_experiment_gap_alter_setting_ball_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='solenoid_drop_time',
            field=models.FloatField(default=0.2, help_text="How long the solenoid will be 'open' to drop balls"),
        ),
    ]
