# Generated by Django 4.1.2 on 2023-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_setting_solenoid_drop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='board_length',
            field=models.FloatField(default=50.0, help_text='Available length to measure on (in cm) - e.g. 50.0'),
        ),
        migrations.AddField(
            model_name='setting',
            name='stepper_motor_halfstep_sleep_time',
            field=models.FloatField(default=0.005, help_text='Sleep time between each half step => lower = faster,higher = slower. Should be between 0.002 and 0.04.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='solenoid_drop_time',
            field=models.FloatField(default=0.2, help_text="How long the solenoid will be 'open' to drop balls in seconds - e.g. 0.15"),
        ),
    ]
